version: '3.9'

services:
  visualizer:
    image: ghcr.io/lux/visualizer:${VISUALIZER_DOCKER_TAG:-latest}
    pull_policy: always
    platform: linux/amd64
    restart: always
    container_name: 'visualizer'
    env_file:
      -  ../envs/common-visualizer.env
