blank_issues_enabled: false
contact_links:
  - name: Feature Request
    url: https://luxdefi.canny.io/feature-requests
    about: Request a feature or enhancement
  - name: Ask a question
    url: https://github.com/orgs/luxdefi/discussions
    about: Ask questions and discuss topics with other community members
  - name: Join our Discord Server
    url: https://discord.gg/luxdefi
    about: The official Explorer Discord community
